import type { Metadata } from "next";
import { Mulish } from 'next/font/google'
import "./globals.css";

const mulish = Mulish({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700','800'],
  display: 'swap',
  variable: "--font-mulish"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mulish.variable}`}>
        {children}
      </body>
    </html>
  );
}
